#!/bin/zsh -i


cd $HOME

export PLAN9=${PLAN9:-/usr/local/plan9}
export NAMESPACE=/tmp/ns.$USER.default
mkdir -p $NAMESPACE

if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi

export NAMESPACE=$(9 namespace)

$HOME/bin/darwin/9term &
exit 0
