#!/bin/bash -l

PLAN9=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PATH=$PATH:$PLAN9/bin

export PLAN9
export PATH

SHELL=$PLAN9/bin/rc
export SHELL

exec $PLAN9/bin/acmesrv "$@"
